dist: trusty
language: ruby
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - DRIVER=google-chrome TZ=Europe/Berlin
addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
        key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - google-chrome-stable
      - yarn
matrix:
    fast_finish: true
    allow_failures:
      - rvm: ruby-head
before_install:
  # yarn is in /usr/local/bin/yarn version 1.3.2 and is not a package
  # must remove this zombie for new yarn to work
  - sudo rm -f /usr/local/bin/yarn
  - gem install bundler
  - nvm install 10
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn install
  - bundle exec rails db:setup
  # - if [[ "$DRIVER" == "google-chrome" ]]; then bundle exec chromedriver-update; fi
  # - if [[ "$DRIVER" == "google-chrome" ]]; then bundle exec chromedriver --version; fi
  # - if [[ "$DRIVER" == "google-chrome" ]]; then google-chrome --version; fi
script:
  # Run rails tests
  # - bundle exec rails test
  # Check if assets can be compiled for production
  - bin/rails assets:precompile RAILS_ENV=production SECRET_KEY_BASE=secret
deploy:
  provider: heroku
  api_key:
    secure: jdUwnAvQqm2TISvEPzcAMvQfG/0doI9SjY0cXoCdc8UbqgAP4NHgg3+dWz4zdg3auzUFz5RgiWwU12ef8mexuIfoMfCN8zZDcDl7X+fC9YF7iAGBzB1h0EX8Z4vx3GMcRBqTLRAxiDF9YEuFelFxyS3BMlQmYS6zlfff7c2yCpjq4bK9a28B/o6icA4iTAQniUg4SXLC5cC+C6ANsPLtlaSLmTdZkMUftae4wpBU/w2b7CgNXXGMGSchYWUGdseG6tjH8/Znl8+FaF6IpLEYc1mdNzwD05Y54bYnmLpIid/T529UU+TvQV3lOA5GYaBK2xHwbmWZ1QCb/Ig1UAqyoeCzJZqs7mmqoudrkvs1utsbk/DzJyp8AoU+F36Iv7cHirJ73hVXYAqgkhH8kg3Lj/yEvU0lFfrD0Y+3T/FXgBHH0pB8musFt1AO89aRLQ7tdNuawWWEINJqAZZ9a1AQSY13qnTs8aFTC+WX1ITUsQoZraB80Q6v/O79Yl8Ywg4e3IVQgN13MyWI2uJ9FbeYZCMeshIMSXBnV7UKK0aGwCZ4QtxqK9axm6m9WVdZknZJwhrIjy951cKXCouq8zeHfEtPiCR3c+4ifDEDolvhCp8ZDvKELd8cuNPXN3319R8wqgveen0rKGRphmsSA+e6B19DDRdZ8KJLIKXfDPYCFsU=
  app:
    master: hyperstack-website
    edge: hyperstack-website-edge
  on:
    rvm: 2.5.1
